### ISSUE TITLE
llvm-project-install is empty

### ISSUE THREAD

**Issue by AbduKT** [Python-for-HPC/PyOMP#1]
When I try to run build.sh, the llvm-project-install folder is empty

**Comment by SHF101202021** [comment]
@AbduKT 
I looks like that downloading zipped code cannot include redirected project
You may download each missing folder by yourself can unzip in the corresponding empty folder

**Comment by zafar-hussain** [comment]
@AbduKT 

I reckon PyOMP has found a new home,

Have a look at [Python-for-HPC](https://github.com/Python-for-HPC/PyOMP)

cheers

**Comment by NathanCummings** [comment]
When cloning a repo with submodules, you need to pass the `--recursive-submodules` flag:
`git clone --recurse-submodules https://github.com/Python-for-HPC/PyOMP.git`

**Comment by ggeorgakoudis** [comment]
Closed as stale, we're streamlining our installation process through conda
