### ISSUE TITLE
PyOMP:Numba 0.57 doesn't load correctly

### ISSUE THREAD

**Issue by JS-WRF-SBM** [Python-for-HPC/PyOMP#6]
Hi All, 

I’ve installed PyOMP within a clean conda env: `conda install -c python-for-hpc -c conda-forge --override-channels pyomp`.
Jupyterlab and ipykernel were also installed. 
Upon running a basic PI example, loading numba throws an error: `Numba needs NumPy 1.24 or less`.

Details:
The numpy & numba versions within the PyOMP virtual env:
```
(intel_PyOMP) jacobs@JS:~/Python_Playground$ conda list | grep numb
numba                     0.57_pyomp      np1.22py3.9h84b9e52_0.57_pyomp    python-for-hpc
(intel_PyOMP) jacobs@JS:~/Python_Playground$ conda list | grep numpy
numpy                     1.24.4          py310ha4c1d20_0    conda-forge 
```

The python interpreter points correctly to the installed PyOMP env:
```
(intel_PyOMP) jacobs@JS:~/Python_Playground$ which python3
/home/jacobs/miniforge3/envs/intel_PyOMP/bin/python3
```

However, loading the numpy lib points to the main file system rather then the virtual env:
```
import numpy as np
print(np.__file__)
```
>` /home/jacobs/.local/lib/python3.10/site-packages/numpy/__init__.py`

Loading numba throws an error:
```
import numba as nb
print(nb.__file__)
```
>`ImportError: Numba needs NumPy 1.24 or less`

**Comment by JS-WRF-SBM** [comment]
@ggeorgakoudis 

This seems to solve the issue.
Now, when I load `numpy` and `numba`, these are loaded from the PyOMP virtual env. 
```
/home/jacobs/miniforge3/envs/intel_PyOMP/lib/python3.10/site-packages/numpy/__init__.py
/home/jacobs/miniforge3/envs/intel_PyOMP/lib/python3.10/site-packages/numba/__init__.py
```

I'm not sure what I did different during installation. Any best practice to prevent this behavior from happening again (for different Conda env)?
Thank you, greatly appreciated!

**Comment by ggeorgakoudis** [comment]
Generally, installation to .local should be avoided. Instead, the recommendation is to use Python's virtual environments (`venv`) or conda environments. Otherwise, the environment is not "clean".

**Comment by ggeorgakoudis** [comment]
Thanks @JS-WRF-SBM, feel free to report back to us! I'm closing this issue.
